# This helper script takes the .mol2 file of the ligand to be docked and generates both .pdbqt files for docking and GAFF2 topologies for the MD
# In this version I am using my fork of acpype package that allows choosing the type of atom/bond prediction
# Until this feature is implemented in the main package you can use my fork from https://github.com/Mishakolok/acpype

import sys
import os
NAME_mol2 = sys.argv[1] # Name of the .mol2 file
NAME = NAME_mol2.split(".mol2")[0]
PATH_TO_DOCKING = sys.argv[2] # Path of the working docking directory
PATH_TO_MD = sys.argv[3] # Path of the working MD directory # Path to the script for the generation of .pdbqt ligand file for docking
PATH_ADFR = sys.argv[4] # Path to ADFR/bin
acpype_path = f"/home/biomd/Documents/GitHub/acpype/run_acpype.py" # Path to the acpype runfile
os.system(f"echo Paths are {NAME=} {PATH_TO_DOCKING=} {PATH_TO_MD=}")

# You can use additional command line options available for Acpype for the generation
# -c {gas,bcc,user}
#    charge method: gas, bcc (default), user (user's
#    charges in mol2 file)
# -r PREDINDEX
#    atom type and bond type prediction index: 0-no
#    assignment, 1-atom type, 2-full bond types, 3-part
#    bond types, 4-atom and full bond type (default),
#    5-atom and part bond type

# Use Acpype to generate GAFF2 parameterized ligand topologies
os.system(f"{acpype_path} -i {NAME_mol2} -c user -f -r 5")

acpype_folder = f"{NAME}.acpype" # Obtained results from acpype

os.system(f" echo Generated GAFF2 topologies for {NAME}!")


os.system(f"mkdir {NAME}_export") # File with exported data
os.system(f"cp {NAME}.mol2 {NAME}_export/{NAME}.mol2") # export original mol2 file for further docking
os.system(f"cp {acpype_folder}/{NAME}_user_gaff2.mol2 {NAME}_export/{NAME}_gaff.mol2") # GAFF2 parameter file for debug

# Here we export itp topology files for MD using GROMACS. You can use other files generated by Acpype for different programs
# Keep in mind that GAFF2 topologies require AmberFF14SB force field installed
os.system(f"cp {acpype_folder}/{NAME}_GMX.itp {NAME}_export/{NAME}_GMX.itp")
os.system(f"cp {acpype_folder}/posre_{NAME}.itp {NAME}_export/posre_{NAME}.itp")


os.system(f"cp {NAME}_export/{NAME}.mol2 {PATH_TO_DOCKING}/")
os.system(f"cp {NAME}_export/posre_{NAME}.itp {NAME}_export/{NAME}_GMX.itp {PATH_TO_MD}/")
os.system(f"echo Moved resulting files in folders for {NAME}!")

